




SELECT 
	b.WORK_DATE, 
	b.WORK_SHIFT,
	a.SITE_ID,
	a.PROPOSED_ID,
	b.DRILL_METHOD,
	b.DIAMETER,
	b.RIG_NO,
	b.DRILL_COMPANY,
	b.DEPTH_FROM,
	b.DEPTH_TO,
	ROUND(b.DEPTH_TO-b.DEPTH_FROM,2) AS INV,
	c.PVC,
	d.OM,
	e.DHSurvey
FROM 
	XPPL_EXPGEO_DB.dbo.GB_SITE a,
	XPPL_EXPGEO_DB.dbo.GB_SITE_DETAIL b
	LEFT OUTER JOIN (
						SELECT 
							SITE_ID,
							WORK_DATE,
							WORK_SHIFT,
							Qty AS PVC
						FROM 
							XPPL_EXPGEO_DB.dbo.GB_DRILLING_DETAIL
						WHERE 
							ITEMS ='PVC'
					) AS c ON c.SITE_ID = b.SITE_ID AND c.WORK_DATE = b.WORK_DATE AND c.WORK_SHIFT = b.WORK_SHIFT

	LEFT OUTER JOIN (
						SELECT 
							SITE_ID,
							WORK_DATE,
							WORK_SHIFT,
							COUNT(DEPTH_FROM) AS OM
						FROM 
							XPPL_EXPGEO_DB.dbo.GB_DRILLING_DETAIL
						WHERE 
							ITEMS ='OM'
						GROUP BY 
							SITE_ID,
							WORK_DATE,
							WORK_SHIFT
					) AS d ON d.SITE_ID = b.SITE_ID AND d.WORK_DATE = b.WORK_DATE AND d.WORK_SHIFT = b.WORK_SHIFT
	
	LEFT OUTER JOIN (
						SELECT 
							SITE_ID,
							WORK_DATE,
							WORK_SHIFT,
							COUNT(DEPTH_FROM) AS DHSurvey
						FROM 
							XPPL_EXPGEO_DB.dbo.GB_DRILLING_DETAIL
						WHERE 
							ITEMS ='DH Survey'
						GROUP BY 
							SITE_ID,
							WORK_DATE,
							WORK_SHIFT
					) AS e ON e.SITE_ID = b.SITE_ID AND e.WORK_DATE = b.WORK_DATE AND e.WORK_SHIFT = b.WORK_SHIFT
WHERE 
	a.SITE_ID = b.SITE_ID
	--AND a.HOLE_STATUS ='Completed'
	AND b.DEPTH_FROM < b.DEPTH_TO
	AND b.DRILL_TYPE ='D'
	--AND b.WORK_DATE BETWEEN '2019/04/01' AND '2019/06/30'
	AND a.SITE_ID IN('DD19BPZ468','DD19BPZ469','DD19BPZ470')
ORDER BY 
	a.SITE_ID,
	b.WORK_DATE,
	b.DEPTH_FROM